# Generated by Django 3.2.7 on 2021-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_rename_password_wishlist_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imageURL',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='websiteURL',
            field=models.CharField(max_length=2000),
        ),
    ]
