# Generated by Django 3.2.7 on 2021-10-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_user_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='password',
            new_name='itemId',
        ),
    ]
